### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: azure.iot.device.common.transport_exceptions.ProtocolProxyError
  fullName: azure.iot.device.common.transport_exceptions.ProtocolProxyError
  inheritance:
  - inheritance:
    - inheritance:
      - inheritance:
        - type: builtins.object
        type: builtins.BaseException
      type: builtins.Exception
    type: azure.iot.device.common.chainable_exception.ChainableException
  langs:
  - python
  module: azure.iot.device.common.transport_exceptions
  name: ProtocolProxyError
  source:
    id: ProtocolProxyError
    path: azure-iot-device\azure\iot\device\common\transport_exceptions.py
    remote:
      branch: master
      path: azure-iot-device\azure\iot\device\common\transport_exceptions.py
      repo: https://github.com/Azure/azure-iot-sdk-python
    startLine: 52
  summary: 'All proxy-related errors.

    TODO : Not sure what to name it here. There is a class called Proxy Error already
    in Pysocks'
  syntax:
    content: ProtocolProxyError(message=None, cause=None)
  type: class
  uid: azure.iot.device.common.transport_exceptions.ProtocolProxyError
references: []
