### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.network.v2019_02_01.models.error.Error
  - azure.mgmt.network.v2019_02_01.models.error.ErrorException
  fullName: azure.mgmt.network.v2019_02_01.models.error
  langs:
  - python
  module: azure.mgmt.network.v2019_02_01.models.error
  name: error
  source:
    id: error
    path: azure-mgmt-network\azure\mgmt\network\v2019_02_01\models\error.py
    remote:
      branch: master
      path: azure-mgmt-network\azure\mgmt\network\v2019_02_01\models\error.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.network.v2019_02_01.models.error
references:
- fullName: azure.mgmt.network.v2019_02_01.models.error.Error
  isExternal: false
  name: Error
  parent: azure.mgmt.network.v2019_02_01.models.error
  uid: azure.mgmt.network.v2019_02_01.models.error.Error
- fullName: azure.mgmt.network.v2019_02_01.models.error.ErrorException
  isExternal: false
  name: ErrorException
  parent: azure.mgmt.network.v2019_02_01.models.error
  uid: azure.mgmt.network.v2019_02_01.models.error.ErrorException
