### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.network.v2019_02_01.models.error_response.ErrorResponse
  - azure.mgmt.network.v2019_02_01.models.error_response.ErrorResponseException
  fullName: azure.mgmt.network.v2019_02_01.models.error_response
  langs:
  - python
  module: azure.mgmt.network.v2019_02_01.models.error_response
  name: error_response
  source:
    id: error_response
    path: azure-mgmt-network\azure\mgmt\network\v2019_02_01\models\error_response.py
    remote:
      branch: master
      path: azure-mgmt-network\azure\mgmt\network\v2019_02_01\models\error_response.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.network.v2019_02_01.models.error_response
references:
- fullName: azure.mgmt.network.v2019_02_01.models.error_response.ErrorResponse
  isExternal: false
  name: ErrorResponse
  parent: azure.mgmt.network.v2019_02_01.models.error_response
  uid: azure.mgmt.network.v2019_02_01.models.error_response.ErrorResponse
- fullName: azure.mgmt.network.v2019_02_01.models.error_response.ErrorResponseException
  isExternal: false
  name: ErrorResponseException
  parent: azure.mgmt.network.v2019_02_01.models.error_response
  uid: azure.mgmt.network.v2019_02_01.models.error_response.ErrorResponseException
