### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.network.v2018_04_01.models.error_py3.Error
  - azure.mgmt.network.v2018_04_01.models.error_py3.ErrorException
  fullName: azure.mgmt.network.v2018_04_01.models.error_py3
  langs:
  - python
  module: azure.mgmt.network.v2018_04_01.models.error_py3
  name: error_py3
  type: module
  uid: azure.mgmt.network.v2018_04_01.models.error_py3
references:
- fullName: azure.mgmt.network.v2018_04_01.models.error_py3.Error
  isExternal: false
  name: Error
  parent: azure.mgmt.network.v2018_04_01.models.error_py3
  uid: azure.mgmt.network.v2018_04_01.models.error_py3.Error
- fullName: azure.mgmt.network.v2018_04_01.models.error_py3.ErrorException
  isExternal: false
  name: ErrorException
  parent: azure.mgmt.network.v2018_04_01.models.error_py3
  uid: azure.mgmt.network.v2018_04_01.models.error_py3.ErrorException
